server:
  port: 8091

spring:
  application:
    name: order-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.200:3306/shop-product?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    hibernate: #jpa
      ddl-auto: update
    dialect: org.hibernate.dialect.MySQL8Dialect
  cloud:
    nacos: #注册中心
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        port: 9999 #跟控制台交流的端口
        dashboard: localhost:8080 # 指定控制台服务的地址
logging:
  level:
    # feign日志以什么级别监控那个接口
    com.service.PaymentFeignService: debug